# -*- coding: utf-8 -*-
"""Copy of Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10uB5QoZqSRy4s35pyUoUP61CyPXEC24R
"""

!pip install -q ultralytics

from ultralytics import YOLO
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import os

from zipfile import ZipFile

with ZipFile("/content/food_img_data_resized (1).zip","r") as zip_ref:
    zip_ref.extractall("/content")

model = YOLO("yolov8n-cls.pt")

model.train(
    data="/content/food_img_data_resized",   # Dataset folder
    epochs=30,
    imgsz=224,
    batch=32,
    device=0
)

import glob

best_model = glob.glob("/content/runs/classify/**/weights/best.pt", recursive=True)

print(best_model)

model = YOLO(best_model[0])

nutrition = pd.read_excel("/content/Food_Nutrition_Table_Veg_NonVeg.xlsx")

nutrition.head()

from google.colab import files

uploaded = files.upload()

# Get uploaded image name
image_path = next(iter(uploaded))

print("Selected Image:", image_path)

"""To ensure the `model` is defined, run the following cell. This cell loads the best-trained weights into a `YOLO` model instance."""

model = YOLO(best_model[0])

image_path = '/content/WhatsApp Image 2026-07-14 at 9.01.25 PM.jpeg'
results = model.predict(
    source=image_path,
    conf=0.5
)

image_path = '/content/WhatsApp Image 2026-07-14 at 9.01.25 PM.jpeg'
results = model.predict(
    source=image_path,
    conf=0.5
)

predicted_class = results[0].names[results[0].probs.top1]

print("Predicted Food:", predicted_class)

img = cv2.imread(image_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(6,6))
plt.imshow(img)
plt.axis("off")
plt.title(predicted_class)
plt.show()

food = nutrition[
    nutrition["Food Item"].str.lower() ==
    predicted_class.lower()
]

if len(food) > 0:

    print("\nFood:", food.iloc[0]["Food Item"])
    print("Calories :", food.iloc[0]["Calories (kcal)"])
    print("Protein  :", food.iloc[0]["Protein (g)"])
    print("Carbs    :", food.iloc[0]["Carbohydrates (g)"])
    print("Fat      :", food.iloc[0]["Fat (g)"])

else:
    print("Nutrition information not found.")

results = model.predict(
    source="/content/WhatsApp Image 2026-07-14 at 9.01.25 PM.jpeg",
    save=True
)

!pip install -q gradio

import gradio as gr
from PIL import Image
import pandas as pd

# nutrition = pd.read_excel("/content/Food_Nutrition_Table_Veg_NonVeg.xlsx")
# model = YOLO(best_model[0])

def predict_food(image):

    results = model.predict(image, conf=0.5)

    predicted_class = results[0].names[results[0].probs.top1]
    confidence = float(results[0].probs.top1conf) * 100

    food = nutrition[
        nutrition["Food Item"].str.lower() == predicted_class.lower()
    ]

    if not food.empty:
        nutrition_text = f"""
Food : {food.iloc[0]['Food Item']}

Calories : {food.iloc[0]['Calories (kcal)']} kcal

Protein : {food.iloc[0]['Protein (g)']} g

Carbohydrates : {food.iloc[0]['Carbohydrates (g)']} g

Fat : {food.iloc[0]['Fat (g)']} g
"""
    else:
        nutrition_text = "Nutrition information not found."

    return (
        predicted_class,
        f"{confidence:.2f} %",
        nutrition_text
    )

demo = gr.Interface(
    fn=predict_food,
    inputs=gr.Image(type="pil", label="Upload Food Image"),
    outputs=[
        gr.Textbox(label="Predicted Food"),
        gr.Textbox(label="Confidence"),
        gr.Textbox(label="Nutrition Information", lines=8)
    ],
    title="Food Detection and Nutrition Information"
)

demo.launch()